name: alcl_web
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  banners: ^0.3.0
  hexcolor: ^2.0.6
  flutter_svg: ^1.0.3
  easy_dynamic_theme: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Maersk Headline
      fonts:
        - asset: assets/fonts/MaerskHeadline-Light.ttf
        - asset: assets/fonts/MaerskHeadline-Lightitalic.ttf
        - asset: assets/fonts/MaerskHeadline-Regular.ttf
        - asset: assets/fonts/MaerskHeadline-Italic.ttf
          style: italic
        - asset: assets/fonts/MaerskHeadline-Bold.ttf
          weight: 700
        - asset: assets/fonts/MaerskHeadline-Bolditalic.ttf
          style: italic
          weight: 700
    - family: Maersk Text
      fonts:
        - asset: assets/fonts/MaerskText-Light.ttf
        - asset: assets/fonts/MaerskText-LightItalic.ttf
        - asset: assets/fonts/MaerskText-Regular.ttf
        - asset: assets/fonts/MaerskText-Italic.ttf
          style: italic
        - asset: assets/fonts/MaerskText-Bold.ttf
          weight: 700
        - asset: assets/fonts/MaerskText-BoldItalic.ttf
          style: italic
          weight: 700

